### ISSUE TITLE
Idempotency Key issue on Cancel Payment

### ISSUE THREAD

**Issue by samjgriffin89** [square/square-dotnet-sdk#13]
Hello,

I'm using the nuget packaged 5.0.0 in our .net core application, and find that when I run our integration tests, cancel payment is failing due to the idempotency_key not being present. I'm not seeing a way to set that since we're just passing down the paymentId here:

https://github.com/square/square-dotnet-sdk/blob/842c4a35c3c43d6c970a49fff8b4c8eb9b6e374b/doc/payments.md#cancel-payment

Error: 
HTTP/1.1 400 Bad Request
{"errors": [{"code": "VALUE_EMPTY","detail": "Field must not be blank","field": "idempotency_key","category": "INVALID_REQUEST_ERROR"}]}

Does a model need to be attached to this so we can build in the idempotency key here?

**Comment by StephenJosey** [comment]
In the source I see two functions with models: `CancelPaymentAsync` and `CancelPaymentByIdempotencyKeyAsync`. If you're using the former, it shouldn't need an `idempotency_key`. I tested calling it, and it succeeded with just a `paymentId` as the documentation suggest. Could you provide a code snippet of what you're trying to do that causes this error?

**Comment by samjgriffin89** [comment]
`var client = new SquareClient.Builder()
                .Timeout(TimeSpan.FromMilliseconds(_clientConfiguration.TimeoutMilliseconds))
                .Environment(_environment)
                .AccessToken(accessToken)
                .Build();

            try
            {
                var response = await client.PaymentsApi.CancelPaymentAsync(paymentId);
                return response;
            }
            catch (ApiException ex)
            {
                int statusCode = ex.ResponseCode;
                _logger.LogError($"There was an issue canceling the square payment with response code {statusCode}", ex);
                throw;
            }`

When I run that call through our integration tests, that 400 above is what I'm getting in return. Could it be how our sandbox environment is set up?

**Comment by samjgriffin89** [comment]
Found another issue that I believe was the root cause not passing the id properly. Thanks for the help.
