### ISSUE TITLE
Async best practices - CancellationToken, .Result 

### ISSUE THREAD

**Issue by jonstelly** [square/square-dotnet-sdk#2]
### .Result
All of the references to `task.Result` should probably be changed to `task.ConfigureAwait(false).GetAwaiter().GetResult()` to [help callers avoid deadlocks](https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f)

### Cancellation
(All?) Async methods should take a CancellationToken parameter to [support cancellation](https://johnthiriet.com/cancel-asynchronous-operation-in-csharp/).  In most cases the parameter can probably be added with a default like this:

```
public async Task<RegisterDomainResponse> RegisterDomainAsync(RegisterDomainRequest body)
```

becomes

```
public async Task<RegisterDomainResponse> RegisterDomainAsync(RegisterDomainRequest body, CancellationToken cancellation = default)
```

and cancellation gets passed through to any methods that take a CancellationToken parameter.

**Comment by shaofu88** [comment]
Thanks for the feedback! We have an action item to look into this and see what we can do in the upcoming releases.

**Comment by jonstelly** [comment]
Thanks.  One other suggestion... all of the example code where .Result is used, just change the examples to be async.  I bet most people using this SDK will be using it from an async context, and if someone needs the non-async they can convert to using the GetAwaiter().GetResult().  This keeps your examples showing the suggested way to use the library and if someone is copy/pasting code then they'll at least get pushed in the right direction:

```csharp
var body = new RegisterDomainRequest.Builder(
        "example.com")
    .Build();

try
{
    RegisterDomainResponse result = applePayApi.RegisterDomainAsync(body).Result;
}
catch (ApiException e){};
```

becomes

```csharp
var body = new RegisterDomainRequest.Builder(
        "example.com")
    .Build();

try
{
    RegisterDomainResponse result = await applePayApi.RegisterDomainAsync(body);
}
catch (ApiException e){};
```

**Comment by jessdelacruzsantos** [comment]
The cancellation token parameter has ben added.
