### ISSUE TITLE
Incorrect names for CustomerCreationSource - Missing Underscores

### ISSUE THREAD

**Issue by jsgoupil** [square/square-dotnet-sdk#27]
This page https://github.com/square/square-dotnet-sdk/blob/master/doc/models/customer-creation-source.md mentions names that might be incorrect? It seems it's missing the underscore?

`THIRDPARTY` -> `THIRD_PARTY`
`INSTANTPROFILE` -> `INSTANT_PROFILE`
etc.

**Comment by sseaman** [comment]
Thanks for reporting! We'll work on fixing it in an upcoming update.

**Comment by jessdelacruzsantos** [comment]
@jsgoupil  We have made the fix to our documentation. Thanks again for reporting.
