### ISSUE TITLE
Painful API usage when ApiException is raised. Difficult to get the main data.

### ISSUE THREAD

**Issue by jsgoupil** [square/square-dotnet-sdk#29]
When an error occurs, you raise an `ApiException`. I'm not going to ask you to change that, that would be quite the breaking change.
But now the API does not work intuitively as expected.

```Csharp
var result = await squareClient.PaymentsApi.CreatePaymentAsync(body);
// I will never be able to get result.Errors here, since you raise an exception. So there is no point to expose the Errors in this return?
```

Nevertheless, I would like to get the data you send back in `Payment` with this API. It is difficult to get the main data. I have to play with your classes that feel quite internal instead of giving me the data easily.

```Csharp
try
{
    var squareClient = await GetSquareClientAsync(contractorId);
    var result = await squareClient.PaymentsApi.CreatePaymentAsync(body);
    return new SquareServerResponse<Payment>
    {
        // This property will never be populated. Why bother?
        // Will you ever return an error here when you have 200-208 status code?
        Errors = result.Errors, 
        Data = result.Payment
    };
}
catch (Square.Exceptions.ApiException ex)
{
    var errors = ex.Errors;
    Square.Models.Payment data = null;

    // Painful dance to get the body so I can get the returned data.
    if (ex.HttpContext.Response is Square.Http.Response.HttpStringResponse httpStringResponse)
    {
        var response = Square.Utilities.ApiHelper.JsonDeserialize<Square.Models.CreatePaymentResponse>(httpStringResponse.Body);
        data = response.Payment;
    }

    return new SquareServerResponse<Payment>
    {
        Errors = errors,
        Data = data
    };
}
catch (Exception ex)
{
    logger.LogError(ex, "ProcessPaymentAsync failed. ContractorId: {ContractorId}", contractorId);
    throw;
}
```

**Comment by jessdelacruzsantos** [comment]
Hello @jsgoupil, what is the information you are trying to access? For Square's creation apis we either respond with an object of the created resource (status code 200s) or an array of errors (status code 400s/500s), but not both. So, if an exception is thrown due to an error, there wouldn't be a resource object in the response.

You can test out calls to CreatePayment using our technical references [API explorer](https://developer.squareup.com/explorer/square/payments-api/create-payment)

**Comment by jsgoupil** [comment]
In case of an error (status 400), **you do** throw an exception. **You do NOT** return an array of errors.

In case of an exception, your REST api MAY return a resource and errors.
In this case, the data actually returned from your API is not easily accessible. Please analyze this screenshot.

![image](https://user-images.githubusercontent.com/808649/86972594-0e3db880-c128-11ea-95b4-329add10d21c.png)

The code shows that you will NEVER return an error, but you will throw an exception.
Then the code also shows that you will not allow mt to get the "payment" data visible in the Fiddler.

**Comment by jessdelacruzsantos** [comment]
@jsgoupil  Thank you for bringing this to our attention, we're working on a fix to address your concerns.

**Comment by jessdelacruzsantos** [comment]
Hello @jsgoupil , we've added a `Data` field on API exceptions. This field is populated if `payment` field in he json response of an exception.

https://github.com/square/square-dotnet-sdk/blob/master/Square/Exceptions/ApiException.cs#L81

**Comment by jsgoupil** [comment]
@jessdelacruzsantos thanks for this. It looks a bit of a code smell don't you think? Your Exception reaches in a potential payment body without the knowledge of any API call you made ...

**Comment by jessdelacruzsantos** [comment]
We'll be moving towards a more generalized solution in the future. Hopefully this unblocks you!
