### ISSUE TITLE
Revoke Token error

### ISSUE THREAD

**Issue by bronthulke** [square/square-dotnet-sdk#3]
I'm migrating to this from Square.Connect, and when trying to do a revoke of a token (my first thing i'm attempting to test), I get an error from the call to RevokeTokenAsync, but it's not very helpful unfortunately:

> HTTP Response Not OK

How can I debug what this may be?  

Here is my code:

```
SquareClient client = new SquareClient.Builder()
                              .Environment(Square.Environment.Sandbox)
                              .Build();

                IOAuthApi oAuthApi = client.OAuthApi;

                var body = new RevokeTokenRequest.Builder()
                    .ClientId(ConfigurationManager.AppSettings["SquareApplicationId"])
                    .AccessToken(currentUser.ConnectedPaymentGatewayUserPublishableKey)
                    .Build();
                string authorization = ConfigurationManager.AppSettings["SquareApplicationSecret"];

                RevokeTokenResponse revokeResponse = await oAuthApi.RevokeTokenAsync(body, authorization);

```

I can confirm that all variables and config values are being pulled in correctly, and it was working prevoiusly using the Square.Connect library.

Thanks!

**Comment by shaofu88** [comment]
@bronthulke, Thank you for trying out our new SDK!
 
If an API fails, it will throw an `ApiException`, and you can access the errors with `ApiException.Errors`. Hope that can help you troubleshoot!

Also don't forget to reference our documentation for usage. https://developer.squareup.com/reference/square/oauth-api/revoke-token

Does your `authorization` string start with "Client " and APPLICATION_SECRET?

**Comment by bronthulke** [comment]
OK thanks, I've found the errors in the exception now, and it was indeed a "bad_request.invalid_parameter" due to the ""bad authorization header".

The documentation had confused me as to whether or not I needed to explicitly include the "Client" prefix or whether it would be added automatically by the SDK. Now that I see this error, I have added it and it's working.

**Comment by sseaman** [comment]
@bronthulke Do you have a suggestion on improving the docs for this issue?  We'd be happy to hear your suggestions and try and improve things

**Comment by bronthulke** [comment]
> @bronthulke Do you have a suggestion on improving the docs for this issue? We'd be happy to hear your suggestions and try and improve things

Apologies for not getting back to you over January.  I'm having a chat with some Square devs today and will try to formulate words around how the docs may have been clearer for me, a lowly integration developer 😂

**Comment by sseaman** [comment]
Hey bron, as I was one of the people who you talked to, I've got your notes.  Thanks and we'll see what we can do on our end to clean this up a bit!

**Comment by bronthulke** [comment]
Haha as of this morning I hadn't connected the handler "sseaman" with you :-D Fantastic!
