### ISSUE TITLE
Offer a main property on the location

### ISSUE THREAD

**Issue by jsgoupil** [square/square-dotnet-sdk#36]
With your latest release 6.1.0, you offer `main_location_id` on the Merchant.
However, I had never queried the merchant before, only the locations. It would be beneficial to add a `main` property on the data being returned when querying all location.

I would expect to see `"main": true` on one of them.

**Comment by StephenJosey** [comment]
Thanks for the feedback! I'll be sure to pass this along to the appropriate team.

**Comment by StephenJosey** [comment]
Closing this as I realize this is actually more of an API request than an SDK request.
