### ISSUE TITLE
Use with ASP.NET MVC 5

### ISSUE THREAD

**Issue by jmawebtech** [square/square-dotnet-sdk#41]
Hi,

I see that this package requires .NET Standard 2.0. Is there a way to use this with ASP.NET 5? My concern is your project adds references to many assembles to my project. Do you have a ASP.NET MVC 5 build?

**Comment by StephenJosey** [comment]
What .NET Framework does MVC 5 use? .NET Standard 2.0 requires .NET 4.6.1 or higher (per Microsoft docs: https://docs.microsoft.com/en-us/dotnet/standard/net-standard), so if your .NET MVC 5 uses 4.6.1 or higher, you should be able to use the .NET SDK.

**Comment by jmawebtech** [comment]
I was hoping there was a way not to add reference to so many assemblies. I use .NET 4.61.
