### ISSUE TITLE
Consider returning empty collections instead of null

### ISSUE THREAD

**Issue by RyanMarcotte** [square/square-dotnet-sdk#42]
The `Order` object's `LineItems` property (and other `IList<T>` properties by the looks of it) can be `null`.  Please consider returning empty collections instead so that consuming code does not have to be littered with `null` checks.

Or is there a case where there is a semantic difference between `null` and "no items"?

**Comment by StephenJosey** [comment]
Hey @RyanMarcotte thanks for the request! I'm not a C# expert and wanting to correctly escalate this request...from what I know, it seems like this would just change checks from `== null` to `collection.isEmpty()`; is that right or am I misunderstanding?

Regardless, this sounds like it would be quite a breaking change so it would take some work to be done correctly, but I'll pass it along to the owning SDK team to look into.
