### ISSUE TITLE
V1Payment Migrate to Order

### ISSUE THREAD

**Issue by jmawebtech** [square/square-dotnet-sdk#43]
Hi,

I am migrating from your old SDK to the new one.

On the V1Payment, there is a field called ProcessingFee. In the new order object, this field is missing. How do I pull the ProcessingFee on the order object? I am trying to map Square merchant fees on orders.

Also, is there a method call to pull customers in batch by customer ID? If I want to pull customers associated with orders, should I just pull them by date modified or date created?

**Comment by StephenJosey** [comment]
The processing fee is only guaranteed to be accurate in the V2 Payments API (it technically is on some orders, but not guaranteed to be accurate). The V1 Payment id and V2 Payment id should be equal, although note that V2 Payments do not currently support cash/other type of payments (which there wouldn't be a processing fee on anyway, but I think it's worth noting).

No way to retrieve customers by batch at this time, unfortunately. On orders or payment objects there should be a `customer_id` if one is associated (there isn't always one associated). Depending on how the payment was created, it will depend on whether it's on the order or payment object.

Please let me know if I misunderstood, or if you have additional questions.

**Comment by sseaman** [comment]
Closing as it looks like the question has been answered.  Please feel free to reopen.
