### ISSUE TITLE
Search for Items and Variation with List of SKUs

### ISSUE THREAD

**Issue by jmawebtech** [square/square-dotnet-sdk#44]
Hi,

If I have a list of SKUs, how do I search for a list of catalog objects?

https://github.com/square/square-dotnet-sdk/blob/master/doc/catalog.md#search-catalog-items

**Comment by StephenJosey** [comment]
There's no way to search multiple SKUs at one time; you can use `SearchCatalogItems` and pass in one SKU as the `TextFilter` of the body (`SearchCatalogItemsRequest`).
