### ISSUE TITLE
API for settlement report

### ISSUE THREAD

**Issue by jmawebtech** [square/square-dotnet-sdk#45]
Hi,

What API would I use the pull the Square settlement report? I tried bank accounts, but I get a 404 error on your docs? I want to see the total deposit, whether the sale was a refund or sale, and what order IDs are associated with the Square deposit.

**Comment by StephenJosey** [comment]
You can use the Settlements API to pull Settlement information. If you retrieve a specific settlement then there will be payment_ids associated, so you would need to do a little digging to get to the order_id (ie retrieve the payment, then get the `order_id`). https://github.com/square/square-dotnet-sdk/blob/master/doc/v1-transactions.md#list-settlements

**Comment by sseaman** [comment]
Closing as it looks like the question has been answered.  Please feel free to reopen.
