### ISSUE TITLE
Square Item Categories

### ISSUE THREAD

**Issue by jmawebtech** [square/square-dotnet-sdk#52]
Hi,

My goal is to pull the category associated with item. What call do I use? For all items, the categoryData object is null. In Square, the products have a category. Can I use catalog batch retrieve?

Request:

POST https://connect.squareup.com/v2/catalog/batch-retrieve

Response:

{
  "objects": [
    {
      "type": "ITEM_VARIATION",
      "id": "T75SRU6UTVBASQM3N3XMHCWY",
      "updated_at": "2020-12-12T19:12:34.323Z",
      "version": 1607800354323,
      "is_deleted": false,
      "present_at_all_locations": true,
      "item_variation_data": {
        "item_id": "2UMDGFPW22S3SYOXLN5NHYJ3",
        "name": "Regular",
        "sku": "ZZ4IN",
        "ordinal": 1,
        "pricing_type": "FIXED_PRICING",
        "price_money": {
          "amount": 1695,
          "currency": "USD"
        },
        "location_overrides": [
          {
            "location_id": "YXF0AW2YQ6STM",
            "track_inventory": true,
            "sold_out": true
          }
        ],
        "available_for_booking": false
      }
    },
    {
      "type": "ITEM_VARIATION",
      "id": "EWP4BZJCD4MNYEMNB6VJRGBO",
      "updated_at": "2020-10-18T01:39:12.254Z",
      "version": 1602985152254,
      "is_deleted": false,
      "present_at_all_locations": true,
      "item_variation_data": {
        "item_id": "Z2WCWWH6PJIYGY4POWMEO2UJ",
        "name": "11.5in x 5.75in x 11.75in",
        "sku": "18991.00",
        "ordinal": 1,
        "pricing_type": "FIXED_PRICING",
        "price_money": {
          "amount": 2795,
          "currency": "USD"
        },
        "location_overrides": [
          {
            "location_id": "YXF0AW2YQ6STM",
            "track_inventory": true
          }
        ]
      }
    }
  ],
  "related_objects": [
    {
      "type": "ITEM",
      "id": "2UMDGFPW22S3SYOXLN5NHYJ3",
      "updated_at": "2020-12-12T19:12:34.323Z",
      "version": 1607800354323,
      "is_deleted": false,
      "present_at_all_locations": true,
      "image_id": "N2J57JRZPNSMFAPC74CRRKUS",
      "item_data": {
        "name": "4in ZZ",
        "label_color": "0B8000",
        "visibility": "PRIVATE",
        "available_online": false,
        "available_for_pickup": false,
        "available_electronically": false,
        "category_id": "VKRNR4AD7D5BOGUJARANW3OJ",
        "ordinal": 0,
        "tax_ids": [
          "NDIPTVTGLO6WNAWY2UPSK3W3"
        ],
        "variations": [
          {
            "type": "ITEM_VARIATION",
            "id": "T75SRU6UTVBASQM3N3XMHCWY",
            "updated_at": "2020-12-12T19:12:34.323Z",
            "version": 1607800354323,
            "is_deleted": false,
            "present_at_all_locations": true,
            "item_variation_data": {
              "item_id": "2UMDGFPW22S3SYOXLN5NHYJ3",
              "name": "Regular",
              "sku": "ZZ4IN",
              "ordinal": 1,
              "pricing_type": "FIXED_PRICING",
              "price_money": {
                "amount": 1695,
                "currency": "USD"
              },
              "location_overrides": [
                {
                  "location_id": "YXF0AW2YQ6STM",
                  "track_inventory": true,
                  "sold_out": true
                }
              ],
              "available_for_booking": false
            }
          }
        ],
        "product_type": "REGULAR",
        "skip_modifier_screen": false,
        "ecom_uri": "https://www.livingroomplants.com/product/4in-zz/214",
        "ecom_image_uris": [
          "https://www.livingroomplants.com/uploads/1/3/1/2/131231860/s578358877802100730_p214_i2_w2560.jpeg",
          "https://www.livingroomplants.com/uploads/1/3/1/2/131231860/s578358877802100730_p214_i1_w2560.jpeg",
          "https://www.livingroomplants.com/uploads/1/3/1/2/131231860/s578358877802100730_p214_i3_w2560.jpeg"
        ],
        "ecom_available": true,
        "ecom_visibility": "VISIBLE",
        "legacy_tax_ids": [
          "NDIPTVTGLO6WNAWY2UPSK3W3"
        ]
      }
    },
    {
      "type": "ITEM",
      "id": "Z2WCWWH6PJIYGY4POWMEO2UJ",
      "updated_at": "2020-10-29T03:39:53.068Z",
      "version": 1603942793068,
      "is_deleted": false,
      "present_at_all_locations": true,
      "image_id": "PRCDCQGTAJFLBKVD46U5D52G",
      "item_data": {
        "name": "Shadow Planter",
        "visibility": "PRIVATE",
        "category_id": "UIT4M3J24UXYVIIXMLJ5KXGN",
        "tax_ids": [
          "NDIPTVTGLO6WNAWY2UPSK3W3"
        ],
        "variations": [
          {
            "type": "ITEM_VARIATION",
            "id": "EWP4BZJCD4MNYEMNB6VJRGBO",
            "updated_at": "2020-10-18T01:39:12.254Z",
            "version": 1602985152254,
            "is_deleted": false,
            "present_at_all_locations": true,
            "item_variation_data": {
              "item_id": "Z2WCWWH6PJIYGY4POWMEO2UJ",
              "name": "11.5in x 5.75in x 11.75in",
              "sku": "18991.00",
              "ordinal": 1,
              "pricing_type": "FIXED_PRICING",
              "price_money": {
                "amount": 2795,
                "currency": "USD"
              },
              "location_overrides": [
                {
                  "location_id": "YXF0AW2YQ6STM",
                  "track_inventory": true
                }
              ]
            }
          },
          {
            "type": "ITEM_VARIATION",
            "id": "3MAH37EMRJLGKGYUMP5XBPGH",
            "updated_at": "2020-10-29T03:39:53.068Z",
            "version": 1603942793068,
            "is_deleted": false,
            "present_at_all_locations": true,
            "item_variation_data": {
              "item_id": "Z2WCWWH6PJIYGY4POWMEO2UJ",
              "name": "8in x 3.5in x 8.25in",
              "sku": "18990.00",
              "ordinal": 2,
              "pricing_type": "FIXED_PRICING",
              "price_money": {
                "amount": 1695,
                "currency": "USD"
              },
              "location_overrides": [
                {
                  "location_id": "YXF0AW2YQ6STM",
                  "track_inventory": true
                }
              ]
            }
          }
        ],
        "product_type": "REGULAR",
        "skip_modifier_screen": false,
        "ecom_uri": "https://www.livingroomplants.com/product/shadow-planter/2260",
        "ecom_image_uris": [
          "https://www.livingroomplants.com/uploads/1/3/1/2/131231860/s578358877802100730_p2260_i4_w1500.jpeg",
          "https://www.livingroomplants.com/uploads/1/3/1/2/131231860/s578358877802100730_p2260_i1_w223.jpeg",
          "https://www.livingroomplants.com/uploads/1/3/1/2/131231860/s578358877802100730_p2260_i2_w1500.jpeg",
          "https://www.livingroomplants.com/uploads/1/3/1/2/131231860/s578358877802100730_p2260_i3_w1500.jpeg",
          "https://www.livingroomplants.com/uploads/1/3/1/2/131231860/s578358877802100730_p2260_i5_w1500.jpeg"
        ],
        "ecom_available": true,
        "ecom_visibility": "VISIBLE",
        "legacy_tax_ids": [
          "NDIPTVTGLO6WNAWY2UPSK3W3"
        ]
      }
    }
  ]
}

**Comment by StephenJosey** [comment]
`category_data` would only be present if the Catalog Object were of type `Category`. You can see these have a `category_id`, so you could retrieve those via the `BatchRetrieveCatalogObjects` if you wanted.

**Comment by sseaman** [comment]
Closing as the question has been answered.  Please feel free to reopen if you have additional questions.
