### ISSUE TITLE
V1Settlement API Permission

### ISSUE THREAD

**Issue by jmawebtech** [square/square-dotnet-sdk#53]
Hi,

Let me know if this is the wrong place to post this issue.

If I obtain an access token, what scopes are needed to pull the V1Settlement object? I am trying to pull a deposit from Square with its associated line items. Here is the URL that I use for the code:

https://connect.squareup.com/oauth2/authorize?&client_id={0}&scope=CUSTOMERS_READ+ORDERS_READ+ITEMS_READ+PAYMENTS_READ+MERCHANT_PROFILE_READ+INVENTORY_WRITE

I went here, but I see no permission:

https://developer.squareup.com/docs/oauth-api/square-permissions

Here is my code:

`        
public List<V1Settlement> GetSettlements(List<string> locationIds, DateTime beginTime, DateTime endTime)
        {
            List<V1Settlement> reports = new List<V1Settlement>();

            foreach (string locationId in locationIds)
            {
                List<V1Settlement> settlements = v1TransactionsApi.ListSettlements(locationId, beginTime: beginTime.ToString("o"), endTime: endTime.ToString("o"));

                foreach(V1Settlement settlement in settlements)
                {
                    V1Settlement item;
                    try
                    {
                        item = v1TransactionsApi.RetrieveSettlement(locationId, settlement.Id);
                    }
                    catch(Exception)
                    {
                        continue;
                    }

                    reports.Add(item);
                }
            }

            return reports;
        }
`

**Comment by sseaman** [comment]
Hi @jmawebtech, I'd ask in our public developer slack channel.  This forum is more related to bugs in the SDK.  The slack is buildwithsquare and the channel is #questions
