### ISSUE TITLE
MIA: OrderFulfillment.DeliveryDetails

### ISSUE THREAD

**Issue by giancarloaguilera** [square/square-dotnet-sdk#55]
Hello,

I am getting the error below trying to create an Order using the OrdersApi.CreateOrder function. The OrderFulfillment of my Order is of type DELIVERY. Unlike when the type is PICKUP and I am able to set the OrderFulfillment.PickupDetails, when the type is DELIVERY there is no OrderFulfillment.DeliveryDetails member for me to set. Will it be available any time soon? Thank you

INVALID_REQUEST_ERROR
MISSING_REQUIRED_PARAMETER
Fulfillments of type DELIVERY must have delivery_details supplied.
order.fulfillments[0].delivery_details

**Comment by StephenJosey** [comment]
There is not a type fo `DELIVERY` at the moment, only pickup and shipment. Delivery is not a supported type in the APIs.
https://github.com/square/square-dotnet-sdk/blob/master/doc/models/order-fulfillment.md

**Comment by giancarloaguilera** [comment]
Thanks @StephenJosey. When will it be supported? Is there a roadmap? As you can imagine not having a delivery option, especially during the pandemic, is pretty limiting. Thank you

**Comment by StephenJosey** [comment]
Unfortunately we do not share public timelines since they can change, so I'm not sure when it will be coming.
