### ISSUE TITLE
Question - Can this be used with the square reader?

### ISSUE THREAD

**Issue by peconia** [square/square-dotnet-sdk#56]
Is it possible to use this SDK to connect to the [square reader](https://squareup.com/gb/en/hardware/reader) on Windows 10? Is there any documentation for that available?

Many thanks.

**Comment by StephenJosey** [comment]
No, unfortunately this is not possible within our existing APIs. However, you can use the [Terminal API](https://developer.squareup.com/docs/terminal-api/overview) (which is available in this SDK), to send payment requests to a [Square Terminal](https://squareup.com/shop/hardware/us/en/products/terminal-credit-card-machine) (not a reader).

**Comment by peconia** [comment]
Thanks for the quick response! Was hoping for a Windows integration of the reader only :)
