### ISSUE TITLE
Get Customer Id Batch

### ISSUE THREAD

**Issue by jmawebtech** [square/square-dotnet-sdk#58]
Hi,

My goal is to pull the customer record for each Square order, so I can map the customer name. I have a list of customer Ids, after pulling a bunch of orders. Is there a way to retrieve customers in batch, if I send a list of customer Ids? When orders are created or modified, the customer created_at and updated_at fields are unchanged, so the date query is unreliable.

**Comment by StephenJosey** [comment]
Unfortunately there are no batch customer endpoints at this time (even outside the SDK). This is a known feature request, but since it's not a request for this specific SDK I will be closing this issue. Please let me know if you have additional questions or concerns!
