### ISSUE TITLE
Error: Cycle detected

### ISSUE THREAD

**Issue by karllarssonusawest** [square/square-dotnet-sdk#63]
I'm getting a NU1108, Cycle detected error trying to install any version of the new SDK on a .Net 5 project. The legacy Square Connect packages install fine.
![square-error](https://user-images.githubusercontent.com/17866663/117071772-627fdd80-ace4-11eb-9d7c-9d0bbfd39a49.JPG)

**Comment by StephenJosey** [comment]
From my understanding this typically happens if your project or solution is also named after the library. In this scenario, is your project named "Square"? If so, I think you'll need to rename your project since it conflicts with our SDK's library name.

**Comment by karllarssonusawest** [comment]
That was exactly it. Thanks so much for the prompt reply.
