### ISSUE TITLE
IV1TransactionsApi depcreated

### ISSUE THREAD

**Issue by jmawebtech** [square/square-dotnet-sdk#82]
Hi,

I am using V17 of your SDK. 

IV1TransactionsApi.ListSettlements is listed as obsolete. What is the replacement?

![image](https://user-images.githubusercontent.com/1679993/149825412-c47e8e6f-b278-4b3b-a330-353af24a3e75.png)

**Comment by wolfadex** [comment]
I _think_ this is related to all of the V1 APIs being deprecated though I'm not certain about what the replacement would be. You might find better answers in either our [Forum](https://developer.squareup.com/forums/) or through our [Slack](https://buildwithsquare.slack.com/ssb/redirect).
