### ISSUE TITLE
Refund issue

### ISSUE THREAD

**Issue by EugeneDNG** [square/square-dotnet-sdk#85]
When I attempt a refund with the .NET SDK, spaces are automatically added to fill out the payment_id to reach 25 characters. I’ve confirmed that the payment_id passed do not contain spaces.

{
  "idempotency_key": "c30483c9-6859-4fc9-8f97-f30880b5f106",
  "amount_money": {
    "amount": 100,
    "currency": "USD"
  },
  "payment_id": "1SyX2KZY2rDCUgSVmdzaEMG3uaB                       "
}
![image](https://user-images.githubusercontent.com/81342324/151876923-b94536b1-de47-4550-a87a-2b9071b8767f.png)

**Comment by wolfadex** [comment]
@EugeneDNG we've been unable to replicate this locally so far. Do you have any additional information that might be relevant?

**Comment by wolfadex** [comment]
Closing this issue since there have been no updates in over a month.
