### ISSUE TITLE
CatalogV1Id returns null values

### ISSUE THREAD

**Issue by hudson-its** [square/square-dotnet-sdk#9]
When using the API Explorer on the site, the data populates correctly, but when calling square.CatalogApi.ListCatalog(null, "ITEM"), the CatalogV1IdProp field is always null.

**Comment by StephenJosey** [comment]
Hi @hudson-its can you provide an example? Are you talking about using this: https://developer.squareup.com/reference/square/catalog-api/list-catalog/explorer? I just tested this and see `catalog_v1_ids` with valid ids. Note that there will not be an id if it wasn't created in V1, though.

**Comment by hudson-its** [comment]
@StephenJosey when I check API explorer, I see values for CatalogV1Ids.

```
"catalog_v1_ids": [
        {
          "catalog_v1_id": "13df5c62-4552-4619-addc-28dcd73e7669",
          "location_id": "D77V0TW8FDYKG"
        }
```

When I pull them through ListCatalogAsync in the SDK the CatalogV1IdProp is always null.

![image](https://user-images.githubusercontent.com/47201785/74879463-711fe600-5326-11ea-8927-806ccff10653.png)

**Comment by StephenJosey** [comment]
Hi @hudson-its sorry I misunderstood originally. I see the same thing as you, thanks for reporting. I'll escalate this to make sure it gets resolved.

**Comment by sseaman** [comment]
This issue was fixed in our March 28th release. Please feel free to reopen if you have additional issues.
