### ISSUE TITLE
How to get a list of order ID's created over certain time 

### ISSUE THREAD

**Issue by kayleejacob1** [square/square-dotnet-sdk#98]
How to get a list of order ID's created over certain time 

or how can i get list of all order ID's

**Comment by zenmasterjobo** [comment]
Hello!

This question feels better suited for our [Developer Forums](https://developer.squareup.com/forums) - these forums are monitored by Square Employees and have active engagement from the community

However, to answer your quest I would suggest using the [Search Orders API](https://developer.squareup.com/reference/square/orders-api/search-orders) which allows you to specify filters in your query for dates. [Here](https://developer.squareup.com/explorer/square_2023-03-15/orders-api/search-orders?params=N4IgRg9gJgngCgQwE4ILYFMAu6kGcQBcoAjgK44yGgBmAlgDbZJUhQLYD6mtGHdjOFgGMk6duigd2LXJmSYpmQiABMABhUBmALRqAjLr0AVNWoKnzagHSmAWiAA0IdADtJ0gqo061AFkMmZhamNmr2AL6R4U70EELstBAuHLRQ%2BAQA2iAAMgASAFJ6tgAa%2BQAcAJoAygBqZQDqIAC60SAAbji4iS7KejYg4UA&env=sandbox&v=1) is a link to an API Explorer example that requests all orders between January 1 and April of 2023. If you want to receive all orders you can just leave the start and end times blank.

Cheers!
